version: '3.8'

services:
  divine-ai:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Add your API keys here or use .env file
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BIBLE_API_KEY=${BIBLE_API_KEY}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped